P.app.on("env-ready", function() {
    function t() { console.log(" run cls"), i.attr("style", s), c.attr("style", s) }

    function e(t) { t && (l = {}), P.post("/base/growthsystem/sign/detail", l, function(n) { if (t) { n.ext.issigntoday && $(".bottom-btn-wrapper .go-checkin").addClass("checked-in").text("已打卡"), n.ext.isshowaward && $(".unclock-spirit-mask").show(); var s = P.map(n.ext.users, "id"),
                    h = n.ext.signresultinfo,
                    u = n.ext.signstaticinfo;
                n.ext.isfinish ? ($(".pic-top-wrapper>img").attr("src", "/klian/web/dist/picturebook/marketing/check_card/images/unclock_spirit_4b88daa.jpg"), $(".checkin-content .title").html('连续打卡<span class="continuoussigncount">' + u.continuoussigncount + "</span>天")) : $(".still-continuoussigncount").html(21 - u.continuoussigncount), $(".pic-top-wrapper img").css("visibility", "visible"), $(".signactivecount").text(n.ext.signactivecount); var k = parseInt((new Date).getTime() / 1e3) - h.finishtime;
                $(".user-name").html(s[h.uid].name), $(".recent-time").html(k / 3600 > 1 ? parseInt(k / 3600) + "小时" : (parseInt(k / 60) ? parseInt(k / 60) : 1) + "分钟"), d.title = "我在参加21天绘本打卡挑战，全力解救海精灵！加入我们！" + (u.continuoussigncount ? "今天第" + u.continuoussigncount + "天" : ""), P.app.share(d), console.log(n.ent.items[0].flag), n.ext.issigntoday || (a(), 1 != sessionStorage.poped && (i.attr("style", ""), c.attr("style", ""), sessionStorage.poped = 1)) }
            l.offset = n.ent.offset, l.more = n.ent.more, p = P.map(n.ext.books, "bookid"), r = P.map(n.ext.products, "productid"), o(n.ent.items, t), l.more && e() }, function() {}) }

    function n(t) { P.post("/base/growthsystem/sign/mend", { date: t }, function() { $(".mend-checkin-mask").hide(), PalfishUI.toast("补卡成功"), e(!0) }, function(t) { PalfishUI.toast(t.msg) }) }

    function a() { P.app.native.enabled && P.app.native.appSwitchForeground(function() { e(!0) }), P.post("/ugc/picturebook/dailytask/get", { strategy: 1 }, function(e) { e.ent.isbindwechat || (document.getElementById("bt1").style.visibility = "visible"), $("#cover").attr("src", e.ent.info.cover.tiny); var n = document.getElementsByName("clock");
            P.app.native.enabled ? n[0].onclick = n[1].onclick = n[2].onclick = function() { "none" != i[0].style.display && t(), P.app.native.open("/picturebook/product/record/" + e.ent.info.bookid) } : n[0].href = n[1].href = n[2].href = "../../mobile/record.html?bookid=" + e.ent.info.bookid }, function(t) { PalfishUI.toast(t.msg) }) }

    function o(t, e) { if (t.length) { for (var n = "", a = 0; a < t.length; a++) switch (t[a].flag) {
                case 1:
                    n += '<span class="date-content"><p>今日</p><a class="go-checkin" name="clock">去打卡</a></span>'; break;
                case 2:
                    n += '<span class="date-content"><p>' + new Date(1e3 * t[a].date).pattern("MM月dd日") + '</p><span class="can-checkin" date="' + t[a].date + '">补打卡</span></span>'; break;
                case 3:
                    n += '<span class="date-content"><p>' + new Date(1e3 * t[a].date).pattern("MM月dd日") + '</p><span class="cannot-checkin">补打卡</span></span>'; break;
                case 4:
                    n += t[a].productid ? '<span class="date-content"><p>' + new Date(1e3 * t[a].date).pattern("MM月dd日") + '</p><span class="book-cover-wrapper" productid="' + t[a].productid + '"><img src="' + p[r[t[a].productid].bookid].cover.tiny + '" class="book-cover" alt=""/></span></span>' : '<span class="date-content"><p>' + new Date(1e3 * t[a].date).pattern("MM月dd日") + '</p><img src="/klian/web/dist/picturebook/marketing/check_card/images/correct_icon_01f5975.png" class="checked-in" alt=""></span>' }
            e && $(".date-wrapper").html(""), $(".date-wrapper").append(n), $(".date-wrapper").find(".date-content p").eq(0).html("今日") } } var i = $("#box"),
        c = $("#bg"),
        s = "display:none;";
    $("#cls").click(t), P.account.isLoggedIn() || "palfish" == P.appEnv() || location.replace("../../../kid/mobile/bind_user/login.html?redirecturl=" + location.href), "palfish" != P.appEnv() && $("#hide-in-wechat").css("display", "none"), P.native.enabled || $(".bottom-btn-wrapper").hide(), P.native.enabled && (P.post = P.app.native.nativePost), P.app.analyzeEvent("Clock_Act", "打卡页面进入"); var p, r, l = {},
        d = { avatar: location.protocol + "//" + location.hostname + "/klian/web/dist/picturebook/images/common/picture_book_icon_031358c.jpg", showType: "small-card", url: location.protocol + "//" + location.hostname + "/klian/web/dist/picturebook/marketing/check_card/share.html?uid=" + P.user.id, title: "我在参加21天绘本打卡挑战，全力解救海精灵！加入我们！", description: "有声英文绘本讲解，睡前故事小帮手，孩子的英文秀场。" };
    P.post("/account/login/bind/wechat/kidservice/isbind", { uid: P.user.id }, function(t) { t.ent.ok || ($(".checkin-wrapper").css("margin-top", 100 / 75 + "rem"), $(".bind-wechat-wrapper").show(), $("#bt1").show(), $(".tip-wrapper").addClass("unbind-tip-wrapper")) }), e(!0), P.post("/base/growthsystem/sign/isshare", { src: 2 }, function(t) { t.ent.isshare && $(".bottom-btn-wrapper .show-up").addClass("showed-up") }), $(".container").on("click", ".bottom-btn-wrapper .show-up", function() { P.app.analyzeEvent("Clock_Act", "炫耀一下点击"), d.prompt = !0, d.success = function(t) { void 0 != t && P.post("/base/growthsystem/sign/share", { src: 2, sharetype: 1 }, function() { delete d.channel, P.app.analyzeEvent("Clock_Act", "炫耀一下分享成功"), $(".bottom-btn-wrapper .show-up").addClass("showed-up"), P.app.checkAppMethod("achievement.check") ? window.PalfishBridgeWeb.call("achievement.check", null) : PalfishUI.toast("领取成功~") }) }, P.app.checkAppMethod("env.checkAppInstall") ? P.app.checkAppInstall({ app: "weixin", success: function(t) { t.installed && (d.channel = 1), P.app.share(d), d.prompt = !1 }, failure: function() {} }) : (d.channel = 1, /pad/i.test(navigator.userAgent) && delete d.channel, P.app.share(d)) }).on("click", ".bottom-btn-wrapper .go-checkin", function() { $(this).hasClass("checked-in") && PalfishUI.toast("今日已打卡~") }).on("click", ".rules-btn", function() { location.replace("index.html?rule=1") }).on("click", ".cancel-btn", function() { $(".mend-checkin-mask").hide() }).on("click", ".ok-btn", function() { var t = $(".mend-checkin-date").attr("date") - 0;
        n(t) }).on("click", ".can-checkin", function() { $(".mend-checkin-date").html($(this).prev().html()).attr("date", $(this).attr("date")), $(".mend-checkin-mask").show() }).on("click", ".cannot-checkin", function() { PalfishUI.toast("只能先补最近一天的未打卡哦～") }).on("click", ".close-btn", function() { $(".unclock-spirit-mask").hide() }).on("click", ".unclock-show-up", function() { $(".bottom-btn-wrapper .show-up").click() }).on("click", ".date-content .go-checkin", function() {}).on("click", ".bind-wechat-wrapper", function() { location.href = P.app.checkAppVersion("1.4.14") ? location.protocol + "//" + location.hostname + "/klian/web/dist/m/reading/bind-wechat.html" : location.protocol + "//" + location.hostname + "/klian/web/dist/mobile/marketing/follow_wechat.html" }).on("click", ".book-cover-wrapper", function() { var t = $(this).attr("productid");
        P.app.analyzeEvent("Clock_Act", "点击封面听打卡作品"), P.native.enabled ? P.app.native.open("/picturebook/product/" + t) : location.href = "../../listen_product.html?productid=" + t }) }), Date.prototype.pattern = function(t) { var e = { "M+": this.getMonth() + 1, "d+": this.getDate(), "h+": this.getHours() % 12 == 0 ? 12 : this.getHours() % 12, "H+": this.getHours(), "m+": this.getMinutes(), "s+": this.getSeconds(), "q+": Math.floor((this.getMonth() + 3) / 3), S: this.getMilliseconds() },
        n = { 0: "日", 1: "一", 2: "二", 3: "三", 4: "四", 5: "五", 6: "六" }; /(y+)/.test(t) && (t = t.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length))), /(E+)/.test(t) && (t = t.replace(RegExp.$1, (RegExp.$1.length > 1 ? RegExp.$1.length > 2 ? "星期" : "/u5468" : "") + n[this.getDay() + ""])); for (var a in e) new RegExp("(" + a + ")").test(t) && (t = t.replace(RegExp.$1, 1 == RegExp.$1.length ? e[a] : ("00" + e[a]).substr(("" + e[a]).length))); return t };